# Makefile.in generated by automake 1.11.3 from Makefile.am.
# Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002,
# 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011 Free Software
# Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.



# Process this file with automake to produce Makefile.in

pkgdatadir = $(datadir)/vice
pkgincludedir = $(includedir)/vice
pkglibdir = $(libdir)/vice
pkglibexecdir = $(libexecdir)/vice
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_triplet = x86_64-unknown-linux
host_triplet = x86_64-unknown-linux
subdir = .
DIST_COMMON = README $(am__configure_deps) $(srcdir)/Makefile.am \
	$(srcdir)/Makefile.in $(srcdir)/vice-gtk.spec.in \
	$(srcdir)/vice-mint-sdl.spec.in $(srcdir)/vice-mint.spec.in \
	$(srcdir)/vice.spec.in $(top_srcdir)/configure \
	$(top_srcdir)/src/arch/unix/next_open_rhap/vice.info.in \
	AUTHORS COPYING ChangeLog INSTALL NEWS config.guess config.sub \
	depcomp install-sh missing mkinstalldirs ylwrap
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/acinclude.m4 \
	$(top_srcdir)/configure.in
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
 configure.lineno config.status.lineno
mkinstalldirs = $(SHELL) $(top_srcdir)/mkinstalldirs
CONFIG_HEADER = $(top_builddir)/src/config.h
CONFIG_CLEAN_FILES = vice.spec vice-gtk.spec vice-mint.spec \
	vice-mint-sdl.spec src/arch/unix/next_open_rhap/vice.info
CONFIG_CLEAN_VPATH_FILES =
SOURCES =
DIST_SOURCES =
RECURSIVE_TARGETS = all-recursive check-recursive dvi-recursive \
	html-recursive info-recursive install-data-recursive \
	install-dvi-recursive install-exec-recursive \
	install-html-recursive install-info-recursive \
	install-pdf-recursive install-ps-recursive install-recursive \
	installcheck-recursive installdirs-recursive pdf-recursive \
	ps-recursive uninstall-recursive
RECURSIVE_CLEAN_TARGETS = mostlyclean-recursive clean-recursive	\
  distclean-recursive maintainer-clean-recursive
AM_RECURSIVE_TARGETS = $(RECURSIVE_TARGETS:-recursive=) \
	$(RECURSIVE_CLEAN_TARGETS:-recursive=) tags TAGS ctags CTAGS \
	distdir dist dist-all distcheck
ETAGS = etags
CTAGS = ctags
DIST_SUBDIRS = $(SUBDIRS)
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
distdir = $(PACKAGE)-$(VERSION)
top_distdir = $(distdir)
am__remove_distdir = \
  if test -d "$(distdir)"; then \
    find "$(distdir)" -type d ! -perm -200 -exec chmod u+w {} ';' \
      && rm -rf "$(distdir)" \
      || { sleep 5 && rm -rf "$(distdir)"; }; \
  else :; fi
am__relativize = \
  dir0=`pwd`; \
  sed_first='s,^\([^/]*\)/.*$$,\1,'; \
  sed_rest='s,^[^/]*/*,,'; \
  sed_last='s,^.*/\([^/]*\)$$,\1,'; \
  sed_butlast='s,/*[^/]*$$,,'; \
  while test -n "$$dir1"; do \
    first=`echo "$$dir1" | sed -e "$$sed_first"`; \
    if test "$$first" != "."; then \
      if test "$$first" = ".."; then \
        dir2=`echo "$$dir0" | sed -e "$$sed_last"`/"$$dir2"; \
        dir0=`echo "$$dir0" | sed -e "$$sed_butlast"`; \
      else \
        first2=`echo "$$dir2" | sed -e "$$sed_first"`; \
        if test "$$first2" = "$$first"; then \
          dir2=`echo "$$dir2" | sed -e "$$sed_rest"`; \
        else \
          dir2="../$$dir2"; \
        fi; \
        dir0="$$dir0"/"$$first"; \
      fi; \
    fi; \
    dir1=`echo "$$dir1" | sed -e "$$sed_rest"`; \
  done; \
  reldir="$$dir2"
DIST_ARCHIVES = $(distdir).tar.gz
GZIP_ENV = --best
distuninstallcheck_listfiles = find . -type f -print
am__distuninstallcheck_listfiles = $(distuninstallcheck_listfiles) \
  | sed 's|^\./|$(prefix)/|' | grep -v '$(infodir)/dir$$'
distcleancheck_listfiles = find . -type f -print
ACLOCAL = ${SHELL} /usr/local/src/asid-vice/missing --run aclocal-1.11
AMTAR = $${TAR-tar}
AR = ar
ARCH_DIR = $(top_builddir)/src/arch/unix
ARCH_EXTRA_SUBDIR = gui x11
ARCH_INCLUDES = -I$(top_srcdir)/src/arch/unix
ARCH_LIBS = $(top_builddir)/src/arch/unix/libarch.a $(top_builddir)/src/arch/unix/gui/libarchgui.a $(top_builddir)/src/arch/unix/x11/libx11ui.a $(top_builddir)/src/arch/unix/x11/xaw/libxawui.a $(top_builddir)/src/arch/unix/x11/xaw/widgets/libwidgets.a $(top_builddir)/src/arch/unix/libarch.a $(top_builddir)/src/arch/unix/gui/libarchgui.a $(top_builddir)/src/arch/unix/x11/libx11ui.a
ARCH_MAKE_BINDIST_DIR = 
ARCH_SRC_DIR = $(top_srcdir)/src/arch/unix
AUTOCONF = ${SHELL} /usr/local/src/asid-vice/missing --run autoconf
AUTOHEADER = ${SHELL} /usr/local/src/asid-vice/missing --run autoheader
AUTOMAKE = ${SHELL} /usr/local/src/asid-vice/missing --run automake-1.11
AWK = mawk
BINDIR = 
CATALOGS = 
CATOBJEXT = .gmo
CC = gcc
CCAS = gcc
CCASDEPMODE = depmode=gcc3
CCASFLAGS = -g -O2
CCDEPMODE = depmode=gcc3
CFLAGS = -g -O3 -march=native -Wstrict-prototypes -Wall -Wno-inline
CPP = gcc -E
CPPFLAGS =  
CROSS = false
CXX = g++
CXXCPP = g++ -E
CXXDEPMODE = depmode=gcc3
CXXFLAGS = -g -fno-exceptions -O3 -march=native -Wall -Wno-inline
CYGPATH_W = echo
DATADIRNAME = share
DEBUGBUILD = 0
DEFS = -DHAVE_CONFIG_H
DEPDIR = .deps
DOS2UNIX = dos2unix
DOS_TFE_PCAP_LIB = 
DYNLIB_LIBS = -ldl
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EDITLINE_LIBS = 
EGREP = 
ENABLE_ARCH = yes
EXEEXT = 
FCCACHE = /usr/bin/fc-cache
FFMPEG_AV_CFLAGS = 
FFMPEG_AV_LIBS = 
FFMPEG_INCLUDES = 
FFMPEG_LIBS = 
FFMPEG_SWSCALE_CFLAGS = 
FFMPEG_SWSCALE_LIBS = 
FULLSCREEN_DRIVERS =  vidmode.o xrandr.o
GENCAT = 
GFXOUTPUT_DRIVERS =  pngdrv.o jpegdrv.o
GFXOUTPUT_LIBS = -ljpeg -lpng 
GMOFILES =  da.gmo de.gmo es.gmo fr.gmo hu.gmo it.gmo ko.gmo nl.gmo pl.gmo ru.gmo sv.gmo tr.gmo
GMSGFMT = /usr/bin/msgfmt
GREP = 
GTKGL_CFLAGS = 
GTKGL_LIBS = 
GTK_CFLAGS = 
GTK_LIBS = 
HAVE_READLINE = 
HCRTF = no
HHC = no
INLINE_UNIT_GROWTH = --param inline-unit-growth=60
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
INSTOBJEXT = .mo
INTLDEPS = 
INTLLIBS = 
INTLOBJS = 
IPFC = no
JOY_LIBS = 
LDFLAGS = -lpthread -Wl,--copy-dt-needed-entries
LEX = flex
LEXLIB = -lfl
LEX_OUTPUT_ROOT = lex.yy
LIBOBJS = 
LIBS = -lbsd -lm -ldl 
LINKCC = $(CXX)
LN_S = ln -s
LTLIBOBJS = 
MAKEGUIDE = no
MAKEINFO = ${SHELL} /usr/local/src/asid-vice/missing --run makeinfo
MAKERTF = no
MAX_INLINE_INSN_SINGLE = --param max-inline-insns-single=600
MKDIR_P = /bin/mkdir -p
MKINSTALLDIRS = ./mkinstalldirs
MSGFMT = /usr/bin/msgfmt
NETPLAY_LIBS = -lnet -lbsd -lnsl 
NLS_LOCALEDIR = 
OBJC = gcc
OBJCDEPMODE = depmode=gcc3
OBJCFLAGS = 
OBJEXT = o
PACKAGE = vice
PACKAGE_BUGREPORT = 
PACKAGE_NAME = 
PACKAGE_STRING = 
PACKAGE_TARNAME = 
PACKAGE_URL = 
PACKAGE_VERSION = 
PATH_SEPARATOR = :
PDFTEX = pdftex
PERL = /usr/bin/perl
PKG_CONFIG = /usr/bin/pkg-config
POFILES =  da.po de.po es.po fr.po hu.po it.po ko.po nl.po pl.po ru.po sv.po tr.po
POSUB = po
QUICKTIME_INCLUDES = 
QUICKTIME_LIBS = 
RANLIB = ranlib
READLINE = 
READLINE_LIBS = -lreadline
RESID_DEP = libresid
RESID_DIR = resid
RESID_DTV_DEP = libresiddtv
RESID_DTV_DIR = resid-dtv
RESID_DTV_INCLUDES = -I$(top_builddir)/src/resid-dtv
RESID_DTV_LIBS = $(top_builddir)/src/resid-dtv/libresiddtv.a
RESID_FP_DEP = 
RESID_FP_DIR = 
RESID_FP_INCLUDES = 
RESID_FP_LIBS = 
RESID_INCLUDES = -I$(top_builddir)/src/resid
RESID_LIBS = $(top_builddir)/src/resid/libresid.a
SDL_EXTRA_LIBS = 
SET_MAKE = 
SHELL = /bin/bash
SOUND_AIX_OBJ = 
SOUND_DRIVERS =  soundpulse.o soundalsa.o soundasid.o sounduss.o sounduss.o soundmp3.o lamelib.o
SOUND_HPUX_OBJ = 
SOUND_LIBS =  -lpulse-simple -lpulse -lasound
SOUND_MIDAS_OBJ = 
SOUND_SDL_OBJ = 
SOUND_SGI_OBJ = 
SOUND_USS_OBJ = 
STRIP = strip
TEXI2DVI = texi2dvi
TEXI2IPF = no
TFE_LIBS = 
UI_LIBS = 
UNIX_MACOSX_UITYPE = 
USE_INCLUDED_LIBINTL = 
USE_NLS = yes
VERSION = 2.4
VERSION_RC = 2,4,0,0
VICEDIR = /usr/local/lib64/vice
VICE_SYNC = openGL_sync.o 
VICE_VERSION = 2.4
VICE_VERSION_BUILD = 0
VICE_VERSION_MAJOR = 2
VICE_VERSION_MINOR = 4
VSID_WINRES = 
VTE_CFLAGS = 
VTE_LIBS = 
WINDRES = 
WRC = 
X128_WINRES = 
X64DTV_WINRES = 
X64_WINRES = 
XCBM2_WINRES = 
XCBM5X0_WINRES = 
XGETTEXT = /usr/bin/xgettext
XMKMF = 
XPET_WINRES = 
XPLUS4_WINRES = 
XVIC_WINRES = 
X_CFLAGS = 
X_EXTRA_LIBS = 
X_LIBS =  -lXrandr -lXxf86vm -lGL -lXaw -lXpm -lXmu -lXt -lXv -lXext -lX11 -lSM -lICE -lbsd -lnsl -lreadline
X_PRE_LIBS =  -lSM -lICE
YACC = bison -y
YFLAGS = 
ZLIB_LIBS = -lz
abs_builddir = /usr/local/src/asid-vice
abs_srcdir = /usr/local/src/asid-vice
abs_top_builddir = /usr/local/src/asid-vice
abs_top_srcdir = /usr/local/src/asid-vice
ac_ct_CC = gcc
ac_ct_CXX = g++
ac_ct_sdl_config = 
am__include = include
am__leading_dot = .
am__quote = 
am__tar = $${TAR-tar} chof - "$$tardir"
am__untar = $${TAR-tar} xf -
artsc_config = 
bindir = ${exec_prefix}/bin
build = x86_64-unknown-linux
build_alias = 
build_cpu = x86_64
build_os = linux
build_vendor = unknown
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE}
dvidir = ${docdir}
exec_prefix = ${prefix}
host = x86_64-unknown-linux
host_alias = 
host_cpu = x86_64
host_os = linux
host_vendor = unknown
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = ${SHELL} /usr/local/src/asid-vice/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
mkdir_p = /bin/mkdir -p
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /usr/local
program_transform_name = s,x,x,
psdir = ${docdir}
sbindir = ${exec_prefix}/sbin
sdl_config = 
sharedstatedir = ${prefix}/com
srcdir = .
subdirs =  src/resid src/resid-dtv
sysconfdir = ${prefix}/etc
target_alias = 
top_build_prefix = 
top_builddir = .
top_srcdir = .
vsid_LDFLAGS = 
x128_LDFLAGS = 
x64_LDFLAGS = 
xcbm2_LDFLAGS = 
xpet_LDFLAGS = 
xplus4_LDFLAGS = 
xvic_LDFLAGS = 
SUBDIRS = $(POSUB) src build data man doc

# COMMON_EXTRA_DIST is what used to be the EXTRA_DIST, when adding dist
# files, please add them to the COMMON_EXTRA_DIST list.
COMMON_EXTRA_DIST = .descr \
	AUTHORS \
	build.minix \
	ChangeLog.1 \
	ChangeLog.2 \
	COPYING \
	FEEDBACK \
	Doxyfile \
	INSTALL \
	NEWS \
	vice.spec \
	vice.spec.in \
	vice-gtk.spec \
	vice-gtk.spec.in \
	vice-mint.spec \
	vice-mint.spec.in \
	vice-mint-sdl.spec \
	vice-mint-sdl.spec.in


# PO_EXTRA_DIST is a list of files in the po directory that need to be
# included in the source archive, this list was added to fix the fact that
# 'make dist' only produced a proper/workable source archive when done on a
# *nix platform with nls.
PO_EXTRA_DIST = po/ChangeLog \
	po/Makefile.in.in \
	po/POTFILES.in \
	po/da.po \
	po/de.po \
	po/es.po \
	po/fr.po \
	po/hu.po \
	po/intl2po.c \
	po/it.po \
	po/ko.po \
	po/nl.po \
	po/pl.po \
	po/po2tbl.sed \
	po/ru.po \
	po/sv.po \
	po/tr.po

#EXTRA_DIST = $(COMMON_EXTRA_DIST) $(PO_EXTRA_DIST)
EXTRA_DIST = $(COMMON_EXTRA_DIST)
#X64SC_INCLUDED = no
X64SC_INCLUDED = yes
all: all-recursive

.SUFFIXES:
am--refresh: Makefile
	@:
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      echo ' cd $(srcdir) && $(AUTOMAKE) --gnu'; \
	      $(am__cd) $(srcdir) && $(AUTOMAKE) --gnu \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --gnu Makefile'; \
	$(am__cd) $(top_srcdir) && \
	  $(AUTOMAKE) --gnu Makefile
.PRECIOUS: Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    echo ' $(SHELL) ./config.status'; \
	    $(SHELL) ./config.status;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck

$(top_srcdir)/configure:  $(am__configure_deps)
	$(am__cd) $(srcdir) && $(AUTOCONF)
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	$(am__cd) $(srcdir) && $(ACLOCAL) $(ACLOCAL_AMFLAGS)
$(am__aclocal_m4_deps):
vice.spec: $(top_builddir)/config.status $(srcdir)/vice.spec.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
vice-gtk.spec: $(top_builddir)/config.status $(srcdir)/vice-gtk.spec.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
vice-mint.spec: $(top_builddir)/config.status $(srcdir)/vice-mint.spec.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
vice-mint-sdl.spec: $(top_builddir)/config.status $(srcdir)/vice-mint-sdl.spec.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
src/arch/unix/next_open_rhap/vice.info: $(top_builddir)/config.status $(top_srcdir)/src/arch/unix/next_open_rhap/vice.info.in
	cd $(top_builddir) && $(SHELL) ./config.status $@

# This directory's subdirectories are mostly independent; you can cd
# into them and run `make' without going through this Makefile.
# To change the values of `make' variables: instead of editing Makefiles,
# (1) if the variable is set in `config.status', edit `config.status'
#     (which will cause the Makefiles to be regenerated when you run `make');
# (2) otherwise, pass the desired values on the `make' command line.
$(RECURSIVE_TARGETS):
	@fail= failcom='exit 1'; \
	for f in x $$MAKEFLAGS; do \
	  case $$f in \
	    *=* | --[!k]*);; \
	    *k*) failcom='fail=yes';; \
	  esac; \
	done; \
	dot_seen=no; \
	target=`echo $@ | sed s/-recursive//`; \
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  echo "Making $$target in $$subdir"; \
	  if test "$$subdir" = "."; then \
	    dot_seen=yes; \
	    local_target="$$target-am"; \
	  else \
	    local_target="$$target"; \
	  fi; \
	  ($(am__cd) $$subdir && $(MAKE) $(AM_MAKEFLAGS) $$local_target) \
	  || eval $$failcom; \
	done; \
	if test "$$dot_seen" = "no"; then \
	  $(MAKE) $(AM_MAKEFLAGS) "$$target-am" || exit 1; \
	fi; test -z "$$fail"

$(RECURSIVE_CLEAN_TARGETS):
	@fail= failcom='exit 1'; \
	for f in x $$MAKEFLAGS; do \
	  case $$f in \
	    *=* | --[!k]*);; \
	    *k*) failcom='fail=yes';; \
	  esac; \
	done; \
	dot_seen=no; \
	case "$@" in \
	  distclean-* | maintainer-clean-*) list='$(DIST_SUBDIRS)' ;; \
	  *) list='$(SUBDIRS)' ;; \
	esac; \
	rev=''; for subdir in $$list; do \
	  if test "$$subdir" = "."; then :; else \
	    rev="$$subdir $$rev"; \
	  fi; \
	done; \
	rev="$$rev ."; \
	target=`echo $@ | sed s/-recursive//`; \
	for subdir in $$rev; do \
	  echo "Making $$target in $$subdir"; \
	  if test "$$subdir" = "."; then \
	    local_target="$$target-am"; \
	  else \
	    local_target="$$target"; \
	  fi; \
	  ($(am__cd) $$subdir && $(MAKE) $(AM_MAKEFLAGS) $$local_target) \
	  || eval $$failcom; \
	done && test -z "$$fail"
tags-recursive:
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  test "$$subdir" = . || ($(am__cd) $$subdir && $(MAKE) $(AM_MAKEFLAGS) tags); \
	done
ctags-recursive:
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  test "$$subdir" = . || ($(am__cd) $$subdir && $(MAKE) $(AM_MAKEFLAGS) ctags); \
	done

ID: $(HEADERS) $(SOURCES) $(LISP) $(TAGS_FILES)
	list='$(SOURCES) $(HEADERS) $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	mkid -fID $$unique
tags: TAGS

TAGS: tags-recursive $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	set x; \
	here=`pwd`; \
	if ($(ETAGS) --etags-include --version) >/dev/null 2>&1; then \
	  include_option=--etags-include; \
	  empty_fix=.; \
	else \
	  include_option=--include; \
	  empty_fix=; \
	fi; \
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  if test "$$subdir" = .; then :; else \
	    test ! -f $$subdir/TAGS || \
	      set "$$@" "$$include_option=$$here/$$subdir/TAGS"; \
	  fi; \
	done; \
	list='$(SOURCES) $(HEADERS)  $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	shift; \
	if test -z "$(ETAGS_ARGS)$$*$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  if test $$# -gt 0; then \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      "$$@" $$unique; \
	  else \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      $$unique; \
	  fi; \
	fi
ctags: CTAGS
CTAGS: ctags-recursive $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	list='$(SOURCES) $(HEADERS)  $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	test -z "$(CTAGS_ARGS)$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && $(am__cd) $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) "$$here"

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags

distdir: $(DISTFILES)
	$(am__remove_distdir)
	test -d "$(distdir)" || mkdir "$(distdir)"
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d "$(distdir)/$$file"; then \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -fpR $(srcdir)/$$file "$(distdir)$$dir" || exit 1; \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    cp -fpR $$d/$$file "$(distdir)$$dir" || exit 1; \
	  else \
	    test -f "$(distdir)/$$file" \
	    || cp -p $$d/$$file "$(distdir)/$$file" \
	    || exit 1; \
	  fi; \
	done
	@list='$(DIST_SUBDIRS)'; for subdir in $$list; do \
	  if test "$$subdir" = .; then :; else \
	    test -d "$(distdir)/$$subdir" \
	    || $(MKDIR_P) "$(distdir)/$$subdir" \
	    || exit 1; \
	  fi; \
	done
	@list='$(DIST_SUBDIRS)'; for subdir in $$list; do \
	  if test "$$subdir" = .; then :; else \
	    dir1=$$subdir; dir2="$(distdir)/$$subdir"; \
	    $(am__relativize); \
	    new_distdir=$$reldir; \
	    dir1=$$subdir; dir2="$(top_distdir)"; \
	    $(am__relativize); \
	    new_top_distdir=$$reldir; \
	    echo " (cd $$subdir && $(MAKE) $(AM_MAKEFLAGS) top_distdir="$$new_top_distdir" distdir="$$new_distdir" \\"; \
	    echo "     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)"; \
	    ($(am__cd) $$subdir && \
	      $(MAKE) $(AM_MAKEFLAGS) \
	        top_distdir="$$new_top_distdir" \
	        distdir="$$new_distdir" \
		am__remove_distdir=: \
		am__skip_length_check=: \
		am__skip_mode_fix=: \
	        distdir) \
	      || exit 1; \
	  fi; \
	done
	-test -n "$(am__skip_mode_fix)" \
	|| find "$(distdir)" -type d ! -perm -755 \
		-exec chmod u+rwx,go+rx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec $(install_sh) -c -m a+r {} {} \; \
	|| chmod -R a+r "$(distdir)"

dist-bzip2: distdir
	tardir=$(distdir) && $(am__tar) | BZIP2=$${BZIP2--9} bzip2 -c >$(distdir).tar.bz2
	$(am__remove_distdir)

dist-lzip: distdir
	tardir=$(distdir) && $(am__tar) | lzip -c $${LZIP_OPT--9} >$(distdir).tar.lz
	$(am__remove_distdir)

dist-lzma: distdir
	tardir=$(distdir) && $(am__tar) | lzma -9 -c >$(distdir).tar.lzma
	$(am__remove_distdir)

dist-xz: distdir
	tardir=$(distdir) && $(am__tar) | XZ_OPT=$${XZ_OPT--e} xz -c >$(distdir).tar.xz
	$(am__remove_distdir)

dist-tarZ: distdir
	tardir=$(distdir) && $(am__tar) | compress -c >$(distdir).tar.Z
	$(am__remove_distdir)

dist-shar: distdir
	shar $(distdir) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).shar.gz
	$(am__remove_distdir)

dist-zip: distdir
	-rm -f $(distdir).zip
	zip -rq $(distdir).zip $(distdir)
	$(am__remove_distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	case '$(DIST_ARCHIVES)' in \
	*.tar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).tar.gz | $(am__untar) ;;\
	*.tar.bz2*) \
	  bzip2 -dc $(distdir).tar.bz2 | $(am__untar) ;;\
	*.tar.lzma*) \
	  lzma -dc $(distdir).tar.lzma | $(am__untar) ;;\
	*.tar.lz*) \
	  lzip -dc $(distdir).tar.lz | $(am__untar) ;;\
	*.tar.xz*) \
	  xz -dc $(distdir).tar.xz | $(am__untar) ;;\
	*.tar.Z*) \
	  uncompress -c $(distdir).tar.Z | $(am__untar) ;;\
	*.shar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).shar.gz | unshar ;;\
	*.zip*) \
	  unzip $(distdir).zip ;;\
	esac
	chmod -R a-w $(distdir); chmod a+w $(distdir)
	mkdir $(distdir)/_build
	mkdir $(distdir)/_inst
	chmod a-w $(distdir)
	test -d $(distdir)/_build || exit 0; \
	dc_install_base=`$(am__cd) $(distdir)/_inst && pwd | sed -e 's,^[^:\\/]:[\\/],/,'` \
	  && dc_destdir="$${TMPDIR-/tmp}/am-dc-$$$$/" \
	  && am__cwd=`pwd` \
	  && $(am__cd) $(distdir)/_build \
	  && ../configure --srcdir=.. --prefix="$$dc_install_base" \
	    $(AM_DISTCHECK_CONFIGURE_FLAGS) \
	    $(DISTCHECK_CONFIGURE_FLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) dvi \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) uninstall \
	  && $(MAKE) $(AM_MAKEFLAGS) distuninstallcheck_dir="$$dc_install_base" \
	        distuninstallcheck \
	  && chmod -R a-w "$$dc_install_base" \
	  && ({ \
	       (cd ../.. && umask 077 && mkdir "$$dc_destdir") \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" install \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" uninstall \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" \
	            distuninstallcheck_dir="$$dc_destdir" distuninstallcheck; \
	      } || { rm -rf "$$dc_destdir"; exit 1; }) \
	  && rm -rf "$$dc_destdir" \
	  && $(MAKE) $(AM_MAKEFLAGS) dist \
	  && rm -rf $(DIST_ARCHIVES) \
	  && $(MAKE) $(AM_MAKEFLAGS) distcleancheck \
	  && cd "$$am__cwd" \
	  || exit 1
	$(am__remove_distdir)
	@(echo "$(distdir) archives ready for distribution: "; \
	  list='$(DIST_ARCHIVES)'; for i in $$list; do echo $$i; done) | \
	  sed -e 1h -e 1s/./=/g -e 1p -e 1x -e '$$p' -e '$$x'
distuninstallcheck:
	@test -n '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: trying to run $@ with an empty' \
	       '$$(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	$(am__cd) '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: cannot chdir into $(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	test `$(am__distuninstallcheck_listfiles) | wc -l` -eq 0 \
	   || { echo "ERROR: files left after uninstall:" ; \
	        if test -n "$(DESTDIR)"; then \
	          echo "  (check DESTDIR support)"; \
	        fi ; \
	        $(distuninstallcheck_listfiles) ; \
	        exit 1; } >&2
distcleancheck: distclean
	@if test '$(srcdir)' = . ; then \
	  echo "ERROR: distcleancheck can only run from a VPATH build" ; \
	  exit 1 ; \
	fi
	@test `$(distcleancheck_listfiles) | wc -l` -eq 0 \
	  || { echo "ERROR: files left in build directory after distclean:" ; \
	       $(distcleancheck_listfiles) ; \
	       exit 1; } >&2
check-am: all-am
check: check-recursive
all-am: Makefile
installdirs: installdirs-recursive
installdirs-am:
install-exec: install-exec-recursive
install-data: install-data-recursive
uninstall: uninstall-recursive

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-recursive
install-strip:
	if test -z '$(STRIP)'; then \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	      install; \
	else \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	    "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'" install; \
	fi
mostlyclean-generic:

clean-generic:

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
	-test . = "$(srcdir)" || test -z "$(CONFIG_CLEAN_VPATH_FILES)" || rm -f $(CONFIG_CLEAN_VPATH_FILES)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-recursive

clean-am: clean-generic mostlyclean-am

distclean: distclean-recursive
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -f Makefile
distclean-am: clean-am distclean-generic distclean-tags

dvi: dvi-recursive

dvi-am:

html: html-recursive

html-am:

info: info-recursive

info-am:

install-data-am:

install-dvi: install-dvi-recursive

install-dvi-am:

install-exec-am:

install-html: install-html-recursive

install-html-am:

install-info: install-info-recursive

install-info-am:

install-man:

install-pdf: install-pdf-recursive

install-pdf-am:

install-ps: install-ps-recursive

install-ps-am:

installcheck-am:

maintainer-clean: maintainer-clean-recursive
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf $(top_srcdir)/autom4te.cache
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-recursive

mostlyclean-am: mostlyclean-generic

pdf: pdf-recursive

pdf-am:

ps: ps-recursive

ps-am:

uninstall-am:

.MAKE: $(RECURSIVE_CLEAN_TARGETS) $(RECURSIVE_TARGETS) ctags-recursive \
	install-am install-strip tags-recursive

.PHONY: $(RECURSIVE_CLEAN_TARGETS) $(RECURSIVE_TARGETS) CTAGS GTAGS \
	all all-am am--refresh check check-am clean clean-generic \
	ctags ctags-recursive dist dist-all dist-bzip2 dist-gzip \
	dist-lzip dist-lzma dist-shar dist-tarZ dist-xz dist-zip \
	distcheck distclean distclean-generic distclean-tags \
	distcleancheck distdir distuninstallcheck dvi dvi-am html \
	html-am info info-am install install-am install-data \
	install-data-am install-dvi install-dvi-am install-exec \
	install-exec-am install-html install-html-am install-info \
	install-info-am install-man install-pdf install-pdf-am \
	install-ps install-ps-am install-strip installcheck \
	installcheck-am installdirs installdirs-am maintainer-clean \
	maintainer-clean-generic mostlyclean mostlyclean-generic pdf \
	pdf-am ps ps-am tags tags-recursive uninstall uninstall-am


.PHONY: vsid x64 x64sc x128 x64dtv xvic xpet xplus4 xcbm2 xcbm5x0 c1541 petcat cartconv
vsid:
	(cd src; $(MAKE) vsid-all)

x64:
	(cd src; $(MAKE) x64-all)

x64sc:
	(cd src; $(MAKE) x64sc-all)

x128:
	(cd src; $(MAKE) x128-all)

x64dtv:
	(cd src; $(MAKE) x64dtv-all)

xvic:
	(cd src; $(MAKE) xvic-all)

xpet:
	(cd src; $(MAKE) xpet-all)

xplus4:
	(cd src; $(MAKE) xplus4-all)

xcbm2:
	(cd src; $(MAKE) xcbm2-all)

xcbm5x0:
	(cd src; $(MAKE) xcbm5x0-all)

c1541:
	(cd src; $(MAKE) c1541-all)

petcat:
	(cd src; $(MAKE) petcat-all)

cartconv:
	(cd src; $(MAKE) cartconv)

install: installvice

# If we have no ChangeLog (which should be generated from SVN), generate a
# dummy one.

ChangeLog:
	touch ChangeLog

##bindist:
##	$(SHELL) $(top_srcdir)/src/arch/unix/make-bindist_amiga.sh $(STRIP) $(VICE_VERSION) $(host_cpu) $(host_os) yes nozip $(X64SC_INCLUDED) $(top_srcdir) $(EXEEXT)

##bindistzip:
##	$(SHELL) $(top_srcdir)/src/arch/unix/make-bindist_amiga.sh $(STRIP) $(VICE_VERSION) $(host_cpu) $(host_os) yes zip $(X64SC_INCLUDED) $(top_srcdir) $(EXEEXT)
#bindist:
#	$(SHELL) $(top_srcdir)/src/arch/unix/make-bindist.sh $(STRIP) $(VICE_VERSION) $(host_cpu) $(host_os) yes nozip $(X64SC_INCLUDED) $(top_srcdir) $(EXEEXT)

#bindistzip:
#	$(SHELL) $(top_srcdir)/src/arch/unix/make-bindist.sh $(STRIP) $(VICE_VERSION) $(host_cpu) $(host_os) yes zip $(X64SC_INCLUDED) $(top_srcdir) $(EXEEXT)

##bindist:
##	$(SHELL) $(top_srcdir)/src/arch/unix/make-bindist_beos.sh $(STRIP) $(VICE_VERSION) $(host_cpu) yes nozip $(X64SC_INCLUDED) $(top_srcdir)

##bindistzip:
##	$(SHELL) $(top_srcdir)/src/arch/unix/make-bindist_beos.sh $(STRIP) $(VICE_VERSION) $(host_cpu) yes zip $(X64SC_INCLUDED) $(top_srcdir)
#bindist:
#	$(SHELL) $(top_srcdir)/src/arch/unix/make-bindist.sh $(STRIP) $(VICE_VERSION) $(host_cpu) yes nozip $(X64SC_INCLUDED) $(top_srcdir)

#bindistzip:
#	$(SHELL) $(top_srcdir)/src/arch/unix/make-bindist.sh $(STRIP) $(VICE_VERSION) $(host_cpu) yes zip $(X64SC_INCLUDED) $(top_srcdir)

#bindist:
#	$(SHELL) $(top_srcdir)/src/arch/unix/make-bindist.sh $(STRIP) $(VICE_VERSION_MAJOR) $(VICE_VERSION_MINOR) yes nozip $(X64SC_INCLUDED) $(top_srcdir)

#bindistzip:
#	$(SHELL) $(top_srcdir)/src/arch/unix/make-bindist.sh $(STRIP) $(VICE_VERSION_MAJOR) $(VICE_VERSION_MINOR) yes zip $(X64SC_INCLUDED) $(top_srcdir)

##bindist:
##	$(SHELL) $(top_srcdir)/src/arch/unix/make-bindist_gp2x.sh $(STRIP) $(VICE_VERSION) yes nozip $(top_srcdir)

##bindistzip:
##	$(SHELL) $(top_srcdir)/src/arch/unix/make-bindist_gp2x.sh $(STRIP) $(VICE_VERSION) yes zip $(top_srcdir)
#bindist:
#	$(SHELL) $(top_srcdir)/src/arch/unix/gp2x/make-bindist.sh $(STRIP) $(VICE_VERSION) yes nozip $(top_srcdir)

#bindistzip:
#	$(SHELL) $(top_srcdir)/src/arch/unix/gp2x/make-bindist.sh $(STRIP) $(VICE_VERSION) yes zip $(top_srcdir)

#bindist:
#	$(SHELL) $(top_srcdir)/src/arch/unix/make-bindist_dingoo.sh $(STRIP) $(VICE_VERSION) yes nozip $(top_srcdir)

#bindistzip:
#	$(SHELL) $(top_srcdir)/src/arch/unix/make-bindist_dingoo.sh $(STRIP) $(VICE_VERSION) yes zip $(top_srcdir)

#bindist:
#	$(SHELL) $(top_srcdir)/src/arch/unix/make-bindist_dingoo_native.sh $(STRIP) $(VICE_VERSION) yes nozip $(top_srcdir)

#bindistzip:
#	$(SHELL) $(top_srcdir)/src/arch/unix/make-bindist_dingoo_native.sh $(STRIP) $(VICE_VERSION) yes zip $(top_srcdir)

#bindist:
#	/bin/bash $(top_srcdir)/src/arch/unix/../unix/macosx/make-bindist.sh $(top_srcdir) $(STRIP) $(VICE_VERSION) @ENABLE_ARCH nozip $(X64SC_INCLUDED) 

#bindistzip:
#	/bin/bash $(top_srcdir)/src/arch/unix/../unix/macosx/make-bindist.sh $(top_srcdir) $(STRIP) $(VICE_VERSION) @ENABLE_ARCH zip $(X64SC_INCLUDED) 

##bindist:
##	$(SHELL) $(top_srcdir)/src/arch/unix/make-bindist_skyos.sh $(STRIP) $(VICE_VERSION) $(prefix) yes nozip $(X64SC_INCLUDED) $(top_srcdir)

##bindistzip:
##	$(SHELL) $(top_srcdir)/src/arch/unix/make-bindist_skyos.sh $(STRIP) $(VICE_VERSION) $(prefix) yes zip $(X64SC_INCLUDED) $(top_srcdir)
#bindist:
#	$(SHELL) $(top_srcdir)/src/arch/unix/skyos/make-bindist.sh $(STRIP) $(VICE_VERSION) $(prefix) yes nozip $(X64SC_INCLUDED) $(top_srcdir)

#bindistzip:
#	$(SHELL) $(top_srcdir)/src/arch/unix/skyos/make-bindist.sh $(STRIP) $(VICE_VERSION) $(prefix) yes zip $(X64SC_INCLUDED) $(top_srcdir)

##bindist:
##	$(SHELL) $(top_srcdir)/src/arch/unix/make-bindist_qnx6.sh $(STRIP) $(VICE_VERSION) $(prefix) $(CROSS) yes nozip $(X64SC_INCLUDED) $(top_srcdir) $(MAKE) $(host_cpu)

##bindistzip:
##	$(SHELL) $(top_srcdir)/src/arch/unix/make-bindist_qnx6.sh $(STRIP) $(VICE_VERSION) $(prefix) $(CROSS) yes zip $(X64SC_INCLUDED) $(top_srcdir) $(MAKE) $(host_cpu)
#bindist:
#	$(SHELL) $(top_srcdir)/src/arch/unix/qnx6/make-bindist.sh $(STRIP) $(VICE_VERSION) $(prefix) $(CROSS) yes nozip $(X64SC_INCLUDED) $(top_srcdir) $(MAKE) $(host_cpu)

#bindistzip:
#	$(SHELL) $(top_srcdir)/src/arch/unix/qnx6/make-bindist.sh $(STRIP) $(VICE_VERSION) $(prefix) $(CROSS) yes zip $(X64SC_INCLUDED) $(top_srcdir) $(MAKE) $(host_cpu)

#bindist:
#	$(SHELL) $(top_srcdir)/src/arch/unix/qnx4/make-bindist.sh $(VICE_VERSION) $(prefix) yes nozip $(X64SC_INCLUDED) $(top_srcdir)

#bindistzip:
#	$(SHELL) $(top_srcdir)/src/arch/unix/qnx4/make-bindist.sh $(VICE_VERSION) $(prefix) yes zip $(X64SC_INCLUDED) $(top_srcdir)

#bindist:
#	$(SHELL) $(top_srcdir)/src/arch/unix/hpux/make-bindist.sh $(STRIP) $(PERL) $(VICE_VERSION) $(prefix) $(host_cpu) $(host_os) yes nozip $(X64SC_INCLUDED) $(top_srcdir)

#bindistzip:
#	$(SHELL) $(top_srcdir)/src/arch/unix/hpux/make-bindist.sh $(STRIP) $(PERL) $(VICE_VERSION) $(prefix) $(host_cpu) $(host_os) yes zip $(X64SC_INCLUDED) $(top_srcdir)

##bindist:
##	$(SHELL) $(top_srcdir)/src/arch/unix/make-bindist_scosol.sh $(STRIP) $(VICE_VERSION) $(prefix) $(CROSS) yes nozip $(X64SC_INCLUDED) sol $(infodir) $(mandir) $(top_srcdir) $(MAKE)

##bindistzip:
##	$(SHELL) $(top_srcdir)/src/arch/unix/make-bindist_scosol.sh $(STRIP) $(VICE_VERSION) $(prefix) $(CROSS) yes zip $(X64SC_INCLUDED) sol $(infodir) $(mandir) $(top_srcdir) $(MAKE)
##bindist:
##	$(SHELL) $(top_srcdir)/src/arch/unix/sco_sol/make-bindist.sh $(STRIP) $(VICE_VERSION) $(prefix) $(CROSS) yes nozip $(X64SC_INCLUDED) sol gtk $(infodir) $(mandir) $(top_srcdir) $(MAKE) $(host_cpu) $(host_os)_

##bindistzip:
##	$(SHELL) $(top_srcdir)/src/arch/unix/sco_sol/make-bindist.sh $(STRIP) $(VICE_VERSION) $(prefix) $(CROSS) yes zip $(X64SC_INCLUDED) sol gtk $(infodir) $(mandir) $(top_srcdir) $(MAKE) $(host_cpu) $(host_os)
#bindist:
#	$(SHELL) $(top_srcdir)/src/arch/unix/sco_sol/make-bindist.sh $(STRIP) $(VICE_VERSION) $(prefix) $(CROSS) yes nozip $(X64SC_INCLUDED) sol xaw $(infodir) $(mandir) $(top_srcdir) $(MAKE) $(host_cpu) $(host_os)

#bindistzip:
#	$(SHELL) $(top_srcdir)/src/arch/unix/sco_sol/make-bindist.sh $(STRIP) $(VICE_VERSION) $(prefix) $(CROSS) yes zip $(X64SC_INCLUDED) sol xaw $(infodir) $(mandir) $(top_srcdir) $(MAKE) $(host_cpu) $(host_os)

#bindist:
#	$(SHELL) $(top_srcdir)/src/arch/unix/next_open_rhap/make-bindist.sh $(STRIP) $(VICE_VERSION) $(prefix) yes nozip $(X64SC_INCLUDED) rhapsody $(top_srcdir) $(MAKE)

#bindistzip:
#	$(SHELL) $(top_srcdir)/src/arch/unix/next_open_rhap/make-bindist.sh $(STRIP) $(VICE_VERSION) $(prefix) yes zip $(X64SC_INCLUDED) rhapsody $(top_srcdir) $(MAKE)

#bindist:
#	$(SHELL) $(top_srcdir)/src/arch/unix/next_open_rhap/make-bindist.sh $(STRIP) $(VICE_VERSION) $(prefix) yes nozip $(X64SC_INCLUDED) openstep $(top_srcdir) $(MAKE)

#bindistzip:
#	$(SHELL) $(top_srcdir)/src/arch/unix/next_open_rhap/make-bindist.sh $(STRIP) $(VICE_VERSION) $(prefix) yes zip $(X64SC_INCLUDED) openstep $(top_srcdir) $(MAKE)

#bindist:
#	$(SHELL) $(top_srcdir)/src/arch/unix/next_open_rhap/make-bindist.sh $(STRIP) $(VICE_VERSION) $(prefix) yes nozip $(X64SC_INCLUDED) nextstep $(top_srcdir) $(MAKE)

#bindistzip:
#	$(SHELL) $(top_srcdir)/src/arch/unix/next_open_rhap/make-bindist.sh $(STRIP) $(VICE_VERSION) $(prefix) yes zip $(X64SC_INCLUDED) nextstep $(top_srcdir) $(MAKE)

##bindist:
##	$(SHELL) $(top_srcdir)/src/arch/unix/make-bindist_scosol.sh $(STRIP) $(VICE_VERSION) $(prefix) $(CROSS) yes nozip $(X64SC_INCLUDED) sco5 $(infodir) $(mandir) $(top_srcdir) $(MAKE)

##bindistzip:
##	$(SHELL) $(top_srcdir)/src/arch/unix/make-bindist_scosol.sh $(STRIP) $(VICE_VERSION) $(prefix) $(CROSS) yes zip $(X64SC_INCLUDED) sco5 $(infodir) $(mandir) $(top_srcdir) $(MAKE)
##bindist:
##	$(SHELL) $(top_srcdir)/src/arch/unix/sco_sol/make-bindist.sh $(STRIP) $(VICE_VERSION) $(prefix) $(CROSS) yes nozip $(X64SC_INCLUDED) sco5 gtk $(infodir) $(mandir) $(top_srcdir) $(MAKE) $(host_cpu) $(host_os)

##bindistzip:
##	$(SHELL) $(top_srcdir)/src/arch/unix/sco_sol/make-bindist.sh $(STRIP) $(VICE_VERSION) $(prefix) $(CROSS) yes zip $(X64SC_INCLUDED) sco5 gtk $(infodir) $(mandir) $(top_srcdir) $(MAKE) $(host_cpu) $(host_os)
#bindist:
#	$(SHELL) $(top_srcdir)/src/arch/unix/sco_sol/make-bindist.sh $(STRIP) $(VICE_VERSION) $(prefix) $(CROSS) yes nozip $(X64SC_INCLUDED) sco5 xaw $(infodir) $(mandir) $(top_srcdir) $(MAKE) $(host_cpu) $(host_os)

#bindistzip:
#	$(SHELL) $(top_srcdir)/src/arch/unix/sco_sol/make-bindist.sh $(STRIP) $(VICE_VERSION) $(prefix) $(CROSS) yes zip $(X64SC_INCLUDED) sco5 xaw $(infodir) $(mandir) $(top_srcdir) $(MAKE) $(host_cpu) $(host_os)

##bindist:
##	$(SHELL) $(top_srcdir)/src/arch/unix/make-bindist_scosol.sh $(STRIP) $(VICE_VERSION) $(prefix) $(CROSS) yes nozip $(X64SC_INCLUDED) sco6 $(infodir) $(mandir) $(top_srcdir) $(MAKE)

##bindistzip:
##	$(SHELL) $(top_srcdir)/src/arch/unix/make-bindist_scosol.sh $(STRIP) $(VICE_VERSION) $(prefix) $(CROSS) yes zip $(X64SC_INCLUDED) sco6 $(infodir) $(mandir) $(top_srcdir) $(MAKE)
##bindist:
##	$(SHELL) $(top_srcdir)/src/arch/unix/sco_sol/make-bindist.sh $(STRIP) $(VICE_VERSION) $(prefix) $(CROSS) yes nozip $(X64SC_INCLUDED) sco6 gtk $(infodir) $(mandir) $(top_srcdir) $(MAKE) $(host_cpu) $(host_os)

##bindistzip:
##	$(SHELL) $(top_srcdir)/src/arch/unix/sco_sol/make-bindist.sh $(STRIP) $(VICE_VERSION) $(prefix) $(CROSS) yes zip $(X64SC_INCLUDED) sco6 gtk $(infodir) $(mandir) $(top_srcdir) $(MAKE) $(host_cpu) $(host_os)
#bindist:
#	$(SHELL) $(top_srcdir)/src/arch/unix/sco_sol/make-bindist.sh $(STRIP) $(VICE_VERSION) $(prefix) $(CROSS) yes nozip $(X64SC_INCLUDED) sco6 xaw $(infodir) $(mandir) $(top_srcdir) $(MAKE) $(host_cpu) $(host_os)

#bindistzip:
#	$(SHELL) $(top_srcdir)/src/arch/unix/sco_sol/make-bindist.sh $(STRIP) $(VICE_VERSION) $(prefix) $(CROSS) yes zip $(X64SC_INCLUDED) sco6 xaw $(infodir) $(mandir) $(top_srcdir) $(MAKE) $(host_cpu) $(host_os)

##bindist:
##	$(SHELL) $(top_srcdir)/src/arch/unix/make-bindist_scosol.sh $(STRIP) $(VICE_VERSION) $(prefix) $(CROSS) yes nozip $(X64SC_INCLUDED) sco7 $(infodir) $(mandir) $(top_srcdir) $(MAKE)

##bindistzip:
##	$(SHELL) $(top_srcdir)/src/arch/unix/make-bindist_scosol.sh $(STRIP) $(VICE_VERSION) $(prefix) $(CROSS) yes zip $(X64SC_INCLUDED) sco7 $(infodir) $(mandir) $(top_srcdir) $(MAKE)
##bindist:
##	$(SHELL) $(top_srcdir)/src/arch/unix/sco_sol/make-bindist.sh $(STRIP) $(VICE_VERSION) $(prefix) $(CROSS) yes nozip $(X64SC_INCLUDED) sco7 gtk $(infodir) $(mandir) $(top_srcdir) $(MAKE) $(host_cpu) $(host_os)

##bindistzip:
##	$(SHELL) $(top_srcdir)/src/arch/unix/sco_sol/make-bindist.sh $(STRIP) $(VICE_VERSION) $(prefix) $(CROSS) yes zip $(X64SC_INCLUDED) sco7 gtk $(infodir) $(mandir) $(top_srcdir) $(MAKE) $(host_cpu) $(host_os)
#bindist:
#	$(SHELL) $(top_srcdir)/src/arch/unix/sco_sol/make-bindist.sh $(STRIP) $(VICE_VERSION) $(prefix) $(CROSS) yes nozip $(X64SC_INCLUDED) sco7 xaw $(infodir) $(mandir) $(top_srcdir) $(MAKE) $(host_cpu) $(host_os)

#bindistzip:
#	$(SHELL) $(top_srcdir)/src/arch/unix/sco_sol/make-bindist.sh $(STRIP) $(VICE_VERSION) $(prefix) $(CROSS) yes zip $(X64SC_INCLUDED) sco7 xaw $(infodir) $(mandir) $(top_srcdir) $(MAKE) $(host_cpu) $(host_os)

##bindist:
##	$(SHELL) $(top_srcdir)/src/arch/unix/make-bindist_win32.sh $(STRIP) $(VICE_VERSION) yes nozip $(X64SC_INCLUDED) $(top_srcdir) $(host_cpu)

##bindistzip:
##	$(SHELL) $(top_srcdir)/src/arch/unix/make-bindist_win32.sh $(STRIP) $(VICE_VERSION) yes zip $(X64SC_INCLUDED) $(top_srcdir) $(host_cpu)
##bindist:
##	$(SHELL) $(top_srcdir)/src/arch/unix/make-bindist.sh $(STRIP) $(VICE_VERSION) yes nozip $(X64SC_INCLUDED) $(top_srcdir) $(host_cpu) yes

##bindistzip:
##	$(SHELL) $(top_srcdir)/src/arch/unix/make-bindist.sh $(STRIP) $(VICE_VERSION) yes zip $(X64SC_INCLUDED) $(top_srcdir) $(host_cpu) yes
#bindist:
#	$(SHELL) $(top_srcdir)/src/arch/unix/make-bindist.sh $(STRIP) $(VICE_VERSION) yes nozip $(X64SC_INCLUDED) $(top_srcdir) $(host_cpu) no

#bindistzip:
#	$(SHELL) $(top_srcdir)/src/arch/unix/make-bindist.sh $(STRIP) $(VICE_VERSION) yes zip $(X64SC_INCLUDED) $(top_srcdir) $(host_cpu) no

#bindist:
#	$(SHELL) $(top_srcdir)/src/arch/unix/make-bindist_syllable.sh $(STRIP) $(VICE_VERSION) $(prefix) yes nozip $(X64SC_INCLUDED) $(top_srcdir)

#bindistzip:
#	$(SHELL) $(top_srcdir)/src/arch/unix/make-bindist_syllable.sh $(STRIP) $(VICE_VERSION) $(prefix) yes zip $(X64SC_INCLUDED) $(top_srcdir)

#installvice:
#	@echo this platform doesn\'t use \"make install\", use \"make bindist\" instead

installvice: install-recursive

cleantrans:
	rm `find $(top_srcdir) -name "*.po.c"`

# Manually define the dist targets so the correct tar usage will be used.
dist-gzip:
	$(DOS2UNIX) `find $(top_srcdir) -name "*.sh"`
	$(DOS2UNIX) $(top_srcdir)/src/translate.txt
	$(DOS2UNIX) $(top_srcdir)/doc/vice.texi
	$(MAKE) distdir
	$(AMTAR) chf - $(distdir) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__remove_distdir)

dist dist-all:
	$(DOS2UNIX) `find $(top_srcdir) -name "*.sh"`
	$(DOS2UNIX) $(top_srcdir)/src/translate.txt
	$(DOS2UNIX) $(top_srcdir)/doc/vice.texi
	$(MAKE) distdir
	$(AMTAR) chf - $(distdir) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__remove_distdir)

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
