---
name: test build
on: [push, pull_request]
jobs:
  test-build-latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: test build
        run: ./build.sh
  test-build-2410:
    runs-on: ubuntu-24.10
    steps:
      - uses: actions/checkout@v4
      - name: test build
        run: docker build -f Dockerfile.2410 .
